version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: api-prod
    ports:
      - '6888:6888'
    networks:
      - backend
    env_file:
      - ./.env.production
    depends_on:
      - redis-server
      - mongo
    links:
      - mongo
      - redis-server

  redis-server:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis/conf:/user/local/etc/redis
    networks:
      - backend

  mongo:
    image: mongo:5.0.2
    restart: 'unless-stopped'
    ports:
      - '27017:27017'
    # command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongodb/db:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
