name: API CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploying API
    runs-on: ubuntu-latest
    steps:
      - name: Deploying API
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ vars.location }}
            sudo git remote remove origin
            sudo git remote add origin https://${{ vars.GIT_USERNAME }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{github.event.repository.name}}.git
            sudo git remote set-url origin https://${{ vars.GIT_USERNAME }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{github.event.repository.name}}.git
            sudo git restore .
            sudo git pull origin main
            sudo docker system prune --force
            sudo docker compose -f docker-compose-prod.yml up -d --build api
